---
- hosts: all
  tasks:
    - name: installing_packages
      apt:
        name: git
        state: present
      become: yes
    - name: copy_file
      copy:
        src: /home/ubuntu/file.txt
        dest: /home/ubuntu
    - name: permission_change
      file:
        path: /home/ubuntu/file.txt
        mode: 0777
        owner: root
        group: root
    - name: create_new_file
      copy:
        content: "New filee"
        dest: /home/ubuntu/zzfile.txt
    - name: install_package
      when: ansible_distribution == "centos"
      yum: 
        name: git
        state: present
      become: yes
    - name: install_ubuntu_flavour
      when: ansible_distribution == "Ubuntu"
      apt:
        name: git
        state: present
